version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.10

    working_directory: ~/repo

    steps:
      - add_ssh_keys:
          fingerprints:
            - "6d:28:60:63:0d:1d:ca:2f:fe:bb:80:48:54:95:d4:ab"
      - checkout
      - run: chmod 400 ~/.ssh/id_rsa_6d2860630d1dca2ffebb80485495d4ab
      - run: ls ~/.ssh/
      - run: cat ~/.ssh/id_rsa_6d2860630d1dca2ffebb80485495d4ab
      - run: cat ~/.ssh/known_hosts
      - run: pwd
      - run: ls -a 
      - run: scp -i ~/.ssh/id_rsa_6d2860630d1dca2ffebb80485495d4ab -o StrictHostKeyChecking=no -r public ubuntu@ec2-35-182-2-244.ca-central-1.compute.amazonaws.com:/home/ubuntu/app
workflows:
    version: 2
    just_build:
        jobs:
            - build
